@tool
class_name ItemResource
extends Resource

## Unique identifier for this item
@export var id: String = ""

## Display name
@export var name: String = ""

## Description shown in tooltips
@export_multiline var description: String = ""

## Item icon texture (generated procedurally if null)
@export var icon: Texture2D

## Maximum stack size
@export var stack_size: int = 100

## Item category for organization
@export var category: Enums.ItemCategory = Enums.ItemCategory.RAW_MATERIAL

## Fuel value in kJ (0 if not fuel)
@export var fuel_value: float = 0.0

## Whether this item is a fluid (stored in tanks)
@export var is_fluid: bool = false

## Color used for procedural sprite generation
@export var sprite_color: Color = Color.WHITE

## Get the icon, generating one if needed
func get_icon() -> Texture2D:
	if icon != null:
		return icon
	# Will be generated by SpriteGenerator
	return null

## Check if this item can be used as fuel
func is_fuel() -> bool:
	return fuel_value > 0.0

func _to_string() -> String:
	return "Item<%s>" % id
